### ISSUE TITLE
Money System

### ISSUE THREAD

**Issue by Miningmark** [Krischan-Klug/pocket-pets#21]

**Comment by Miningmark** [comment]
# Money System

## Value Proposition

As a user
I want ,
so that .

## Acceptance Criteria
- Add Money to the Game
- Display yout Money at the Pet Collection Page and Detail Page

## Tasks
- create feature branch feature/Money System
- Create a userObject with Money Key/Value pair
- Display yout Money at the Pet Collection Page and Detail Page
- Create functions to increase and Decrease Money

**Comment by JessicaLoers** [comment]
**Hey Team Pocket 👜 Pets  🐩**

Well done. Here are some suggestions to emphasise the benefits of the feature. 

### Value Proposition

**As a user,**
**I want to use** in-game currency,
**So that I can** revive my pet in the game, enhancing my gameplay experience.

---

### Acceptance Criteria
_Think about how you could formulate the AC more precisely._ 

Here is an example. One of your criteria is: 
- Add money to the game

_Is the user able to add money, or is initial money made available to him?  🤔_ 


**Here are some suggestions**

- Players have a amount of in-game currency (e.g. dollar or bunny ears 😁) at their balance when they open the app
- The player's currency balance is clearly visible on the Pet Collection Page
- Players have the option to revive their pets using a specified amount of in-game currency.
- A clear and intuitive option/button for pet revival  is visible on the Pet Collection Page.
- Upon revival, the pet regains its levels and comes back to life. 
- The bunny ears invested is deducted from the balance. 
- Once the credit has been used up, animals can't be revived.

**Comment by Miningmark** [comment]
# Money System and Pet reanimation

## Value Proposition

As a user
I want to use in-game currency,
So that I can revive my pet in the game, enhancing my gameplay experience.



![Image](https://github.com/Krischan-Klug/pocket-pets/assets/29154263/3d3e3cb5-68b2-4b93-8a75-5ebf5f62dbaf)


![Image](https://github.com/Krischan-Klug/pocket-pets/assets/29154263/c771cb2a-9005-4c76-8611-4dbc46993f99)




## Acceptance Criteria
- The user starts with 250 in-game currency
- Display your Money at the Pet Collection Page
- Pet revive (costs e.g. 200 in-game currency) 
- The pet is revived with 50% health
- Once the credit has been used up, animals can't be revived.
- If you run out of in-game currency and animals or simply want to start again, you can reset the game in the settings.

## Tasks
- create feature branch feature/Money System
- Create a userObject with Money Key/Value pair
- Display your in-game currency at the Pet Collection Page
- Create functions to increase and Decrease Money
- Pet revive with in-game currency Button
- Create a Settings Page with a Reset Button, include a confirm PopUp
