### ISSUE TITLE
Shopping system

### ISSUE THREAD

**Issue by Miningmark** [Krischan-Klug/pocket-pets#28]

**Comment by Miningmark** [comment]
# Shopping system

## Value Proposition

As a user
I want buy better food ,
so that I can use this better food to avoid having to feed for longer.

## Acceptance Criteria
- Add a store to buy food.
- There should be different types of food on offer, which cost different amounts and are of different quality.
- You should be able to choose from your available food at the feed button.

## Tasks
- create feature branch feature/Shopping system
- Create a Shop Page
- Edit the UserObject and add a Inventory{} and in this the Food[] and save every foodoption as a {} with id and quantity
- Create a feed Button PopUp for choose your food

**Comment by JessicaLoers** [comment]
**Well done.**

_Here're some suggestions:_

**As a user**
**I want** to be able to buy high-quality food for my pets,
**so that**  I can use this and that my pet needs to be fed less. 
❓ _Or is it really the case that I no longer need to feed my pets at all?_ 


**Acceptance Criteria**
_The criteria could be formulated a little more precisely and from the **user's point of view - because the user doesn't **add a store**, but the store is available for him to by things.**_

- A "Food Store" section is available, where users can browse available food items.

It would be nice if you could adapt these suggestions and also take them into account for the following future user stories. 

**But all in all, everything is good.**
