### ISSUE TITLE
Seasons of the year

### ISSUE THREAD

**Issue by Krischan-Klug** [Krischan-Klug/pocket-pets#47]
**Value Proposition**

As a petowner i want life the seasons of the year,
that I have more dynamic in my game and

**Acceptance Criteria**

- weather is based on the actual season
- day night cycle is based on the actual season
- a calender and clock to display the actual day / time

**Tasks**

- refactor the time system to a decent calender system
- refactor the day night cycle
- refactor the weather system based on the seasons
- implement a clock and a calender

**Comment by JessicaLoers** [comment]
**Nice one.** 
Of course, I have a few comments that you can take into account. 😁

**In general** 
- Please pay attention to the formatting and consistency of the user stories. 
- It's okay that not every user story has a wire frame - in this case it would be difficult to display with the rudimentary means. But maybe it's nice to mention why it's missing. 


## Value Proposition
⚠️_Could be formulated a little more specifically._
**As a pet owner**
**I want** the game to mimic the real-world seasons and day-night cycles
**so that I** my engagement and immersion is enhanced
