### ISSUE TITLE
Minigame Pet Invaders

### ISSUE THREAD

**Issue by Miningmark** [Krischan-Klug/pocket-pets#54]
# Minigame Pet Invaders

## Value Proposition

As a user
I want to have a Fun minigame like the Space Invaders game,
so that i can earn money to get new items.

## Acceptance Criteria
- Show a description how play the game
- Display the current score prominently.
- Display playercharracter and enemies
- The player character can shoot at enemies
- collision detection between the player-controlled character and enemies
- Show a game over screen when the game end.
- Implement swipe-based OR/AND button-based controls for tile movement.

## Tasks
- create feature branch feature/Minigame - Pet Invaders
- create a GamePage
- Implement input detection logic for player input using either swipe-based or button-based controls.
- Integrate the KaBoom.js library for building the game mechanics.
- Implementation of collision detection between player-controlled character and enemies
- Display the current score prominently on the screen.
- Design and implement a game over screen with the final score displayed.

SAMPLE GAME:
[Space Invaders](https://www.spiele123.com/spiel/space-invaders)

**Comment by Xristof23** [comment]
Hallo,

nice Idea to battle with pets. I also like the overall Idea to earn money for the main part of the game by successfully playing mini games. Some Questions and Suggestions:

- No wireframes?
- If you do not show a wireframe, may a link to a screenshot of a similar game could help? (e. g. Space invaders or one of the clones) because there might be people out there who do not now "Space Invaders"  ;)
- technically, you will need collision detection for player missiles and enemies as well. Also, collision detection is the more technical term and might better be used only in the tasks
- Control acceptance criteria are not completely clear to me ... if to be played on mobiles, will you implement "virtual" buttons, swipe mechanics or both?
- Task to display score is written like an acceptance criterium, overall the tasks could include more technical language

Am looking forward to see this feature impemented, will be fun.
Have fun and keep up the good work!
